<?php

namespace Database\Seeders;

use App\Models\ApplicationLanguage;
use Illuminate\Database\Seeder;

class AppLanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $application_languages = [
            ['application_no' => '3451', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3442', 'language' => 'Spanish', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3452', 'language' => 'English', 'years_studied' => '11', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3452', 'language' => 'Dutch', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3469', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3508', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3494', 'language' => 'English', 'years_studied' => '10', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3494', 'language' => 'Welsh', 'years_studied' => '6', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3494', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3496', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3496', 'language' => 'Welsh', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3530', 'language' => 'Welsh', 'years_studied' => '7', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3530', 'language' => 'Spanish', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3530', 'language' => 'German', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3528', 'language' => 'Mandarin Chinese', 'years_studied' => '8', 'speaking' => 'Good', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3495', 'language' => 'Welsh', 'years_studied' => '12', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3495', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Good'],
            ['application_no' => '3495', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Poor', 'writing' => 'Fair'],
            ['application_no' => '3449', 'language' => 'Gujrati', 'years_studied' => '12', 'speaking' => 'Fluent', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3449', 'language' => 'Arabic', 'years_studied' => '6', 'speaking' => 'Poor', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3526', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3437', 'language' => 'French ', 'years_studied' => '7', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3437', 'language' => 'Irish', 'years_studied' => '7', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3481', 'language' => 'Fench', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3447', 'language' => 'German ', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3447', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3447', 'language' => 'Japanese ', 'years_studied' => '2', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3610', 'language' => 'German', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3610', 'language' => 'German', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3516', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3516', 'language' => 'Irish', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3479', 'language' => 'English', 'years_studied' => '12', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3479', 'language' => 'English', 'years_studied' => '12', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3479', 'language' => 'Spanish', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3436', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3561', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3561', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3561', 'language' => 'Irish', 'years_studied' => '10', 'speaking' => 'Good', 'reading' => 'Poor', 'writing' => 'Fair'],
            ['application_no' => '3472', 'language' => 'English ', 'years_studied' => '7', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3512', 'language' => 'Welsh ', 'years_studied' => '10', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3512', 'language' => 'Spanish', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3512', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3491', 'language' => 'German', 'years_studied' => '4', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3491', 'language' => 'Chinese', 'years_studied' => '0', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3511', 'language' => 'Spanish ', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3511', 'language' => 'Spanish ', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3511', 'language' => 'French ', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3562', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3562', 'language' => 'Irish', 'years_studied' => '14', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3490', 'language' => 'Welsh', 'years_studied' => '1', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3490', 'language' => 'French', 'years_studied' => '7', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Fair'],
            ['application_no' => '3490', 'language' => 'Welsh', 'years_studied' => '6', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3513', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3439', 'language' => 'French', 'years_studied' => '10', 'speaking' => 'Good', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3439', 'language' => 'German', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3507', 'language' => 'German', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3507', 'language' => 'German', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3507', 'language' => 'Irish', 'years_studied' => '10', 'speaking' => 'Fluent', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3619', 'language' => 'Irish ', 'years_studied' => '14', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3619', 'language' => 'French ', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'French ', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3598', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3620', 'language' => 'Welsh', 'years_studied' => '5', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3620', 'language' => 'Old English', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3560', 'language' => 'French', 'years_studied' => '12', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Poor'],
            ['application_no' => '3575', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3575', 'language' => 'Spanish', 'years_studied' => '1', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3603', 'language' => 'Irish', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3603', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3603', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3473', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3552', 'language' => 'English', 'years_studied' => '11', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3552', 'language' => 'spanish', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3552', 'language' => 'French', 'years_studied' => '7', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3552', 'language' => 'Russian', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3435', 'language' => 'Norwegian', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3435', 'language' => 'French', 'years_studied' => '7', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Good'],
            ['application_no' => '3475', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3519', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3500', 'language' => 'German ', 'years_studied' => '5', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3505', 'language' => 'German', 'years_studied' => '6', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3505', 'language' => 'Irish', 'years_studied' => '13', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3519', 'language' => 'Irish ', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3631', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3480', 'language' => 'French', 'years_studied' => '12', 'speaking' => 'Fluent', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3480', 'language' => 'Icelandic', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3480', 'language' => 'Latin', 'years_studied' => '5', 'speaking' => 'Poor', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3585', 'language' => 'German/French/Irish', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3585', 'language' => 'German/French/Irish', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3585', 'language' => 'German/French/Irish', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3560', 'language' => 'Irish', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3583', 'language' => 'German ', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3583', 'language' => 'Mandarin Chinese ', 'years_studied' => '1', 'speaking' => 'Fair', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3629', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3629', 'language' => 'Spanish', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3434', 'language' => 'Korean', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3578', 'language' => 'Welsh', 'years_studied' => '15', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3578', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3578', 'language' => 'Spanish', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3434', 'language' => 'Korean', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3601', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3627', 'language' => 'spanish ', 'years_studied' => '7', 'speaking' => 'Good', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3572', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3572', 'language' => 'Spanish', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3628', 'language' => 'German', 'years_studied' => '12', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3628', 'language' => 'Spanish', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Poor', 'writing' => 'Fair'],
            ['application_no' => '3573', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3573', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3627', 'language' => 'spanish ', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Fluent', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3594', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Fluent', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3594', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Fluent', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3594', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Fluent', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3594', 'language' => 'Urdu ', 'years_studied' => '16', 'speaking' => 'Fluent', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'Korean', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3434', 'language' => 'Korean', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3434', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Poor'],
            ['application_no' => '3434', 'language' => 'German', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3434', 'language' => 'Japanese', 'years_studied' => '1', 'speaking' => 'Fair', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3434', 'language' => 'Korean', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3471', 'language' => 'Mandarin', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3471', 'language' => 'Irish', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3471', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3578', 'language' => 'Italian', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3578', 'language' => 'Italian', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3438', 'language' => 'Irish', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'German', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Poor'],
            ['application_no' => '3498', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Poor'],
            ['application_no' => '3555', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3555', 'language' => 'Irish', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3476', 'language' => 'English', 'years_studied' => '18', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3630', 'language' => 'French', 'years_studied' => '2019', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3630', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3509', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3441', 'language' => 'Korean', 'years_studied' => '1', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3441', 'language' => 'Korean', 'years_studied' => '1', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3441', 'language' => 'German', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3448', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3580', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3664', 'language' => 'welsh ', 'years_studied' => '7', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3664', 'language' => 'welsh ', 'years_studied' => '7', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3664', 'language' => 'spanish ', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3664', 'language' => 'french ', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3665', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3665', 'language' => 'Welsh', 'years_studied' => '13', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'Welsh ', 'years_studied' => '13', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3704', 'language' => 'English', 'years_studied' => '12', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3705', 'language' => 'Ukraine ', 'years_studied' => '1', 'speaking' => 'Fluent', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3705', 'language' => 'Russian', 'years_studied' => '1', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3736', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3767', 'language' => 'English', 'years_studied' => '5', 'speaking' => 'Fluent', 'reading' => '', 'writing' => 'Fluent'],
            ['application_no' => '3767', 'language' => 'English', 'years_studied' => '5', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3767', 'language' => 'Catalan', 'years_studied' => '10', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3721', 'language' => 'German', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3721', 'language' => 'Welsh', 'years_studied' => '10', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3720', 'language' => 'Welsh', 'years_studied' => '7', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3720', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3739', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Good'],
            ['application_no' => '3739', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3739', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3779', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3779', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3779', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3779', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3779', 'language' => 'German', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3737', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3737', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3737', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3737', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3737', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3784', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3784', 'language' => 'German', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3751', 'language' => 'French', 'years_studied' => '10', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3751', 'language' => 'German', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3751', 'language' => 'Spanish', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Poor'],
            ['application_no' => '3774', 'language' => 'Tamil', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3774', 'language' => 'German', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3762', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3762', 'language' => 'Welsh', 'years_studied' => '7', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3762', 'language' => 'Urdu', 'years_studied' => '0', 'speaking' => 'Fluent', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3824', 'language' => 'Irish', 'years_studied' => '14', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3824', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3822', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3822', 'language' => 'Irish', 'years_studied' => '13', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3766', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3826', 'language' => 'Welsh', 'years_studied' => '10', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3826', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3826', 'language' => 'Welsh', 'years_studied' => '10', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3826', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3826', 'language' => 'Spanish', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3818', 'language' => 'Russian ', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3818', 'language' => 'German ', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3818', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3745', 'language' => 'French ', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3823', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3763', 'language' => 'Welsh', 'years_studied' => '18', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3763', 'language' => 'French', 'years_studied' => '11', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3763', 'language' => 'Spanish', 'years_studied' => '11', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3765', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3797', 'language' => 'Portuguese', 'years_studied' => '13', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3797', 'language' => 'Spanish', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3817', 'language' => 'Portuguese', 'years_studied' => '0', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3817', 'language' => 'Spanish', 'years_studied' => '0', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Poor'],
            ['application_no' => '3817', 'language' => 'Italian', 'years_studied' => '0', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3733', 'language' => 'Italian', 'years_studied' => '0', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3743', 'language' => 'French ', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3743', 'language' => 'Spanish ', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3743', 'language' => 'French ', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3810', 'language' => 'Welsh', 'years_studied' => '10', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3810', 'language' => 'Welsh', 'years_studied' => '8', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3854', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3787', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3728', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3765', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3765', 'language' => 'Irish', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3752', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3752', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3752', 'language' => 'French', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'Urdu', 'years_studied' => '17', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3850', 'language' => 'German', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3850', 'language' => 'Irish', 'years_studied' => '12', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => null, 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Good'],
            ['application_no' => '3731', 'language' => 'Urdu', 'years_studied' => '10', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3731', 'language' => 'Urdu', 'years_studied' => '10', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3731', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3849', 'language' => 'Irish', 'years_studied' => '14', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3849', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3727', 'language' => 'German', 'years_studied' => '8', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3727', 'language' => 'German', 'years_studied' => '8', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3727', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3729', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fluent', 'reading' => 'Poor', 'writing' => 'Good'],
            ['application_no' => '3729', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fluent', 'reading' => 'Poor', 'writing' => 'Good'],
            ['application_no' => '3729', 'language' => 'Spanish', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3852', 'language' => 'French', 'years_studied' => '7', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3852', 'language' => 'French', 'years_studied' => '7', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3852', 'language' => 'German', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3852', 'language' => 'German', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3852', 'language' => 'German', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3770', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3770', 'language' => 'Greek ', 'years_studied' => '1', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3815', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3815', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3815', 'language' => 'Latin', 'years_studied' => '4', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3841', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Poor'],
            ['application_no' => '3841', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3841', 'language' => 'Irish', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3841', 'language' => 'Irish', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3841', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'Irish', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'Irish', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '11', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3783', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3829', 'language' => 'Gujarati', 'years_studied' => '5', 'speaking' => 'Fluent', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3794', 'language' => 'French', 'years_studied' => '11', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3816', 'language' => 'french', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3856', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3856', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3840', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'japanese', 'years_studied' => '16', 'speaking' => 'Good', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3855', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'German', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3867', 'language' => 'spanish', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Poor', 'writing' => 'Good'],
            ['application_no' => '3903', 'language' => 'French', 'years_studied' => '0', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3903', 'language' => 'French', 'years_studied' => '11', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3903', 'language' => 'German', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3903', 'language' => 'Spanish', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'German', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3908', 'language' => 'French', 'years_studied' => '7', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3908', 'language' => 'Spanish', 'years_studied' => '0', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3809', 'language' => 'french', 'years_studied' => '2018', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3904', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Poor', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3904', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'japanese', 'years_studied' => '16', 'speaking' => 'Good', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3820', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3916', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '7', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'English', 'years_studied' => '18', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => null, 'language' => 'English', 'years_studied' => '18', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => null, 'language' => 'English', 'years_studied' => '18', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3916', 'language' => 'French', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3916', 'language' => 'Italian', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3916', 'language' => 'British Sign Language', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3746', 'language' => 'French', 'years_studied' => '7', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3894', 'language' => 'French', 'years_studied' => '7', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3832', 'language' => 'English', 'years_studied' => '18', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3832', 'language' => 'spanish', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3780', 'language' => 'french ', 'years_studied' => '5', 'speaking' => 'Fluent', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3865', 'language' => 'Farsi', 'years_studied' => '7', 'speaking' => 'Poor', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3865', 'language' => 'Farsi', 'years_studied' => '7', 'speaking' => 'Poor', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3865', 'language' => 'German', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => '3865', 'language' => 'Farsi', 'years_studied' => '7', 'speaking' => 'Poor', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3912', 'language' => 'English', 'years_studied' => '15', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3912', 'language' => 'Spanish', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3828', 'language' => 'Japanese', 'years_studied' => '16', 'speaking' => 'Good', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3828', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3863', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3863', 'language' => 'French', 'years_studied' => '6', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3863', 'language' => 'Urdu', 'years_studied' => '19', 'speaking' => 'Fluent', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3848', 'language' => 'French ', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3848', 'language' => 'German', 'years_studied' => '2', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3857', 'language' => 'Irish', 'years_studied' => '13', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3857', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3914', 'language' => 'French', 'years_studied' => '15', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3914', 'language' => 'German', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3874', 'language' => 'Irish ', 'years_studied' => '6', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3876', 'language' => 'English ', 'years_studied' => '12', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3876', 'language' => 'French ', 'years_studied' => '8', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3876', 'language' => 'Spanish ', 'years_studied' => '3', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3876', 'language' => 'Russian ', 'years_studied' => '3', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3882', 'language' => 'Irish', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3882', 'language' => 'French', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'Irish', 'years_studied' => '14', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3881', 'language' => 'Irish', 'years_studied' => '14', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3918', 'language' => 'Spanish', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3918', 'language' => 'Spanish', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3910', 'language' => 'English ', 'years_studied' => '9', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3910', 'language' => 'Spanish', 'years_studied' => '6', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Poor'],
            ['application_no' => '3910', 'language' => 'Italian', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'Irish', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3881', 'language' => 'Spanish', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3900', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3922', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3922', 'language' => 'Irish', 'years_studied' => '9', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3898', 'language' => 'Spanish', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3911', 'language' => 'English ', 'years_studied' => '7', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3911', 'language' => 'spanish ', 'years_studied' => '7', 'speaking' => 'Good', 'reading' => 'Fluent', 'writing' => 'Good'],
            ['application_no' => null, 'language' => 'English', 'years_studied' => '7', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3801', 'language' => 'English', 'years_studied' => '7', 'speaking' => 'Fluent', 'reading' => 'Fluent', 'writing' => 'Fluent'],
            ['application_no' => '3801', 'language' => 'Russian', 'years_studied' => '1', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3842', 'language' => 'Spanish', 'years_studied' => '2', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3842', 'language' => 'Frenc', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3842', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => '3842', 'language' => 'German', 'years_studied' => '3', 'speaking' => 'Poor', 'reading' => 'Poor', 'writing' => 'Poor'],
            ['application_no' => null, 'language' => 'Irish', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3873', 'language' => 'Irish', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3811', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Poor'],
            ['application_no' => '3915', 'language' => 'French', 'years_studied' => '12', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => null, 'language' => 'French', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3851', 'language' => 'Mauritian Creole', 'years_studied' => '13', 'speaking' => 'Good', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3851', 'language' => 'French', 'years_studied' => '3', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3915', 'language' => 'French', 'years_studied' => '5', 'speaking' => 'Fair', 'reading' => 'Fair', 'writing' => 'Fair'],
            ['application_no' => '3839', 'language' => 'French', 'years_studied' => '12', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3839', 'language' => 'Irish', 'years_studied' => '4', 'speaking' => 'Good', 'reading' => 'Good', 'writing' => 'Fair'],
            ['application_no' => '3890', 'language' => 'spanish', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3890', 'language' => 'spanish', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
            ['application_no' => '3890', 'language' => 'spanish', 'years_studied' => '4', 'speaking' => 'Fair', 'reading' => 'Good', 'writing' => 'Good'],
        ];
        foreach ($application_languages as $language) {
            try {
                ApplicationLanguage::create($language);
            } catch (\Exception $ex) {
            }
        }
    }
}
