<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DyeoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ribi_dyeo')->truncate();
        $dyeos = [
            ['district_code' => '1060', 'dyeo_name' => 'Jason Gage', 'dyeo_email' => 'jason.gage@sky.com', 'dyeo_contact_no' => '07955480529', 'dyeo_address' => '88 Alder Road', 'dyeo_city' => 'Coventry', 'dyeo_state' => 'West Midlands', 'dyeo_postcode' => 'CV6 7DQ', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 24 7672 1237', 'dyeo_wtel' => '+44 24 7650 6090', 'dyeo_mobile' => '+44 7955 480529', 'dyeo_fax' => '+44 24 7650 6090'],
            ['district_code' => '1010', 'dyeo_name' => 'Iain Gow', 'dyeo_email' => 'iainagow@gmail.com', 'dyeo_contact_no' => '07724 147451', 'dyeo_address' => '74 Milton Road', 'dyeo_city' => 'Kirkcaldy', 'dyeo_state' => 'Fife', 'dyeo_postcode' => 'KY1 1TP', 'dyeo_country' => 'Scotland', 'dyeo_htel' => '+44 1592 265445', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7724 147451', 'dyeo_fax' => ''],
            ['district_code' => '1020', 'dyeo_name' => 'Alistair Mackintosh', 'dyeo_email' => 'ali.mack50@btinternet.com', 'dyeo_contact_no' => '07956 438115', 'dyeo_address' => null, 'dyeo_city' => null, 'dyeo_state' => null, 'dyeo_postcode' => null, 'dyeo_country' => null, 'dyeo_htel' => null, 'dyeo_wtel' => null, 'dyeo_mobile' => null, 'dyeo_fax' => null],
            ['district_code' => '1030', 'dyeo_name' => 'Jacqueline Molyneux', 'dyeo_email' => 'jmoly56@aol.com', 'dyeo_contact_no' => '01670 224410', 'dyeo_address' => '2 Broadoak Mews, Low Westwood', 'dyeo_city' => 'Newcastle upon Tyne', 'dyeo_state' => '', 'dyeo_postcode' => 'NE17 7PF', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 1207 566953', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7968 003591', 'dyeo_fax' => ''],
            ['district_code' => '1040', 'dyeo_name' => 'Graham Horrell', 'dyeo_email' => 'grahamhorrell@hotmail.com', 'dyeo_contact_no' => '07773 428441', 'dyeo_address' => null, 'dyeo_city' => null, 'dyeo_state' => null, 'dyeo_postcode' => null, 'dyeo_country' => null, 'dyeo_htel' => null, 'dyeo_wtel' => null, 'dyeo_mobile' => null, 'dyeo_fax' => null],
            ['district_code' => '1070', 'dyeo_name' => 'Mark Deutsch', 'dyeo_email' => 'mrkdeutsch@aol.com', 'dyeo_contact_no' => '07736 480227', 'dyeo_address' => '1 Hodge Court', 'dyeo_city' => 'Kettering', 'dyeo_state' => 'Northants.', 'dyeo_postcode' => 'NN15 7EZ', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 1536 392060', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7736 480227', 'dyeo_fax' => ''],
            ['district_code' => '1080', 'dyeo_name' => 'Bill Redmayne', 'dyeo_email' => 'rotary1080whr@gmail.com', 'dyeo_contact_no' => '07831 838075', 'dyeo_address' => '', 'dyeo_city' => '', 'dyeo_state' => '', 'dyeo_postcode' => '', 'dyeo_country' => '', 'dyeo_htel' => '', 'dyeo_wtel' => '', 'dyeo_mobile' => '', 'dyeo_fax' => ''],
            ['district_code' => '1090', 'dyeo_name' => 'Alistair KNOX', 'dyeo_email' => 'ajknox@tecose.com', 'dyeo_contact_no' => '07913 632434', 'dyeo_address' => '102 Loddon Bridge Road, Woodley', 'dyeo_city' => 'Reading', 'dyeo_state' => 'Berks.', 'dyeo_postcode' => 'RG5 4AW', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 118 969 6547', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7913 632434', 'dyeo_fax' => ''],
            ['district_code' => '1100', 'dyeo_name' => 'Paul Sherrington', 'dyeo_email' => 'sherrington.paul@sky.com', 'dyeo_contact_no' => '01600 860529', 'dyeo_address' => 'Highfield House, Pheasant Rise', 'dyeo_city' => 'Pencraig', 'dyeo_state' => 'Herefordshire', 'dyeo_postcode' => 'HR9 6HR', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 1989 770911', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7775 804082', 'dyeo_fax' => ''],
            ['district_code' => '1110', 'dyeo_name' => 'Mike Hurley', 'dyeo_email' => 'phluphph@hotmail.com', 'dyeo_contact_no' => '07929 648406', 'dyeo_address' => '43 Washbrook Road', 'dyeo_city' => 'Portsmouth', 'dyeo_state' => 'Hants.', 'dyeo_postcode' => 'PO6 3SA', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 23 9311 1924', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7929 648406', 'dyeo_fax' => ''],
            ['district_code' => '1120', 'dyeo_name' => 'Steve Hanks', 'dyeo_email' => 'steve.d.hanks@gmail.com', 'dyeo_contact_no' => '07752 884547', 'dyeo_address' => null, 'dyeo_city' => null, 'dyeo_state' => null, 'dyeo_postcode' => null, 'dyeo_country' => null, 'dyeo_htel' => null, 'dyeo_wtel' => null, 'dyeo_mobile' => null, 'dyeo_fax' => null],
            ['district_code' => '1130', 'dyeo_name' => 'Di King', 'dyeo_email' => 'di.londonyex@gmail.com', 'dyeo_contact_no' => '07545 575456', 'dyeo_address' => '49 Leinster Avenue', 'dyeo_city' => 'East Sheen', 'dyeo_state' => 'London', 'dyeo_postcode' => 'SW14 7JW', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 20 8876 8997', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7545 575456', 'dyeo_fax' => ''],
            ['district_code' => '1145', 'dyeo_name' => 'Peter King', 'dyeo_email' => 'kingpd@hotmail.com', 'dyeo_contact_no' => '07794 600034', 'dyeo_address' => '49 Leinster Avenue', 'dyeo_city' => 'East Sheen', 'dyeo_state' => 'London', 'dyeo_postcode' => 'SW14 7JW', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 20 8876 8997', 'dyeo_wtel' => '+44 20 7073 4245', 'dyeo_mobile' => '+44 7973 147118', 'dyeo_fax' => ''],
            ['district_code' => '1150', 'dyeo_name' => 'Eric Blackwell', 'dyeo_email' => 'ericblackwell05@gmail.com', 'dyeo_contact_no' => '07737 108486', 'dyeo_address' => '20 Fisher Hill Way, Radyr', 'dyeo_city' => 'Cardiff', 'dyeo_state' => '', 'dyeo_postcode' => 'CF15 8DR', 'dyeo_country' => 'Wales', 'dyeo_htel' => '+44 29 2084 2717', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7737 108486', 'dyeo_fax' => ''],
            ['district_code' => '1160', 'dyeo_name' => 'Mary O\'Mahony', 'dyeo_email' => 'maryberomahony@yahoo.co.uk', 'dyeo_contact_no' => '00353 87 2239629', 'dyeo_address' => '34 Fremont Drive, Bishopstown', 'dyeo_city' => 'Cork', 'dyeo_state' => '', 'dyeo_postcode' => 'T12 K79W', 'dyeo_country' => 'Ireland', 'dyeo_htel' => '', 'dyeo_wtel' => '', 'dyeo_mobile' => '+353 87 2239629', 'dyeo_fax' => ''],
            ['district_code' => '1175', 'dyeo_name' => 'Martin Mather', 'dyeo_email' => 'mjcmather@doctors.org.uk', 'dyeo_contact_no' => '07967 145521', 'dyeo_address' => 'The Old Barn, Higherslade', 'dyeo_city' => 'Ifracombe', 'dyeo_state' => 'Devon', 'dyeo_postcode' => 'EX34 8LJ', 'dyeo_country' => 'UK', 'dyeo_htel' => '01271 864672', 'dyeo_wtel' => '', 'dyeo_mobile' => '07967 145521', 'dyeo_fax' => ''],
            ['district_code' => '1180', 'dyeo_name' => 'Maria Martin', 'dyeo_email' => 'maria.t.martin@btinternet.com', 'dyeo_contact_no' => '07828 970227', 'dyeo_address' => '29 Private Drive', 'dyeo_city' => 'Barnston', 'dyeo_state' => 'Merseyside', 'dyeo_postcode' => 'CH6 11DF', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 151 648 5201', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7828 970227', 'dyeo_fax' => ''],
            ['district_code' => '1190', 'dyeo_name' => 'Patricia Hoggarth', 'dyeo_email' => 'sherwoodseaton@hotmail.com', 'dyeo_contact_no' => '01900 604122', 'dyeo_address' => null, 'dyeo_city' => null, 'dyeo_state' => null, 'dyeo_postcode' => null, 'dyeo_country' => null, 'dyeo_htel' => null, 'dyeo_wtel' => null, 'dyeo_mobile' => null, 'dyeo_fax' => null],
            ['district_code' => '1200', 'dyeo_name' => 'Alison Patrick', 'dyeo_email' => 'alison@alipat.co.uk', 'dyeo_contact_no' => '01225 420245', 'dyeo_address' => null, 'dyeo_city' => null, 'dyeo_state' => null, 'dyeo_postcode' => null, 'dyeo_country' => null, 'dyeo_htel' => null, 'dyeo_wtel' => null, 'dyeo_mobile' => null, 'dyeo_fax' => null],
            ['district_code' => '1210', 'dyeo_name' => 'Hilary Ball', 'dyeo_email' => 'jandhball@aol.com', 'dyeo_contact_no' => '07891 025079', 'dyeo_address' => null, 'dyeo_city' => null, 'dyeo_state' => null, 'dyeo_postcode' => null, 'dyeo_country' => null, 'dyeo_htel' => null, 'dyeo_wtel' => null, 'dyeo_mobile' => null, 'dyeo_fax' => null],
            ['district_code' => '1220', 'dyeo_name' => 'Cas Francis', 'dyeo_email' => 'cas@casinspireme.com', 'dyeo_contact_no' => '07740 302361', 'dyeo_address' => '', 'dyeo_city' => '', 'dyeo_state' => '', 'dyeo_postcode' => '', 'dyeo_country' => '', 'dyeo_htel' => '', 'dyeo_wtel' => '+44 1773 821424', 'dyeo_mobile' => '+44 7747 080415', 'dyeo_fax' => ''],
            ['district_code' => '1230', 'dyeo_name' => 'Iain Shaw', 'dyeo_email' => 'iaintshaw@yahoo.co.uk', 'dyeo_contact_no' => '07746 103235', 'dyeo_address' => null, 'dyeo_city' => null, 'dyeo_state' => null, 'dyeo_postcode' => null, 'dyeo_country' => null, 'dyeo_htel' => null, 'dyeo_wtel' => null, 'dyeo_mobile' => null, 'dyeo_fax' => null],
            ['district_code' => '1240', 'dyeo_name' => 'Peter Dowse', 'dyeo_email' => 'peterdowse69@gmail.com', 'dyeo_contact_no' => '07957 562678', 'dyeo_address' => '14 Stocksfield, Kelvedon Hatch', 'dyeo_city' => 'Brentwood', 'dyeo_state' => 'Essex', 'dyeo_postcode' => 'CM15 0BU', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 1277 374342', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7957 562678', 'dyeo_fax' => ''],
            ['district_code' => '1260', 'dyeo_name' => 'John Hammond', 'dyeo_email' => 'john.hammond1@btinternet.com', 'dyeo_contact_no' => '07545 786647', 'dyeo_address' => '7 Pond Lane', 'dyeo_city' => 'Baldock', 'dyeo_state' => 'Herts.', 'dyeo_postcode' => 'SG7 5AS', 'dyeo_country' => 'UK', 'dyeo_htel' => '+44 1462 894603', 'dyeo_wtel' => '', 'dyeo_mobile' => '+44 7940 548220', 'dyeo_fax' => ''],
            ['district_code' => '1270', 'dyeo_name' => '', 'dyeo_email' => '', 'dyeo_contact_no' => '', 'dyeo_address' => null, 'dyeo_city' => null, 'dyeo_state' => null, 'dyeo_postcode' => null, 'dyeo_country' => null, 'dyeo_htel' => null, 'dyeo_wtel' => null, 'dyeo_mobile' => null, 'dyeo_fax' => null],
            ['district_code' => '1285', 'dyeo_name' => 'Adrian Ramsden', 'dyeo_email' => 'amrams@myway.com', 'dyeo_contact_no' => '01625 668767', 'dyeo_address' => null, 'dyeo_city' => null, 'dyeo_state' => null, 'dyeo_postcode' => null, 'dyeo_country' => null, 'dyeo_htel' => null, 'dyeo_wtel' => null, 'dyeo_mobile' => null, 'dyeo_fax' => null],
        ];
        foreach ($dyeos as $dyeo) {
            DB::table('ribi_dyeo')->insert($dyeo);
        }
    }
}
