<?php

namespace Database\Seeders;

use App\Models\RibiClub;
use App\Models\RibiCyeo;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RibiCyeoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $clubinfo = array(
            array('id' => '1','cyeo_name' => 'Jason Gage','cyeo_sig' => NULL,'cyeo_address' => '88 Alder Road','cyeo_city' => 'Coventry','cyeo_state' => 'West Midlands','cyeo_postcode' => 'CV6 7DQ','cyeo_country' => 'UK','cyeo_htel' => '024 76506090','cyeo_wtel' => '7955480529','cyeo_mobile' => '7955480529','cyeo_fax' => '024 76506090','cyeo_email' => 'jason.gage@sky.com','application_no' => '1','ribi_club_id' => '955','user_id' => '390'),
            array('id' => '2','cyeo_name' => 'Patrick Holloway','cyeo_sig' => NULL,'cyeo_address' => '23 Robindale Avenue, Earley','cyeo_city' => 'READING','cyeo_state' => 'Berks.','cyeo_postcode' => 'RG6 7JR','cyeo_country' => 'UK','cyeo_htel' => '+44 118 966 3642','cyeo_wtel' => '','cyeo_mobile' => '+44 7557 398015','cyeo_fax' => NULL,'cyeo_email' => 'rbnholloway@aol.com','application_no' => '2980','ribi_club_id' => '1430','user_id' => '391'),
            array('id' => '3','cyeo_name' => 'Shaun Green','cyeo_sig' => NULL,'cyeo_address' => '5 Tower Close','cyeo_city' => 'Ramsey','cyeo_state' => 'Cambridgeshire','cyeo_postcode' => 'PE26 1BX','cyeo_country' => 'U.K.','cyeo_htel' => '01487 710573','cyeo_wtel' => '','cyeo_mobile' => '6.54655E+11','cyeo_fax' => NULL,'cyeo_email' => 'shaungreen@ramseyrotary.co.uk','application_no' => '3037','ribi_club_id' => NULL,'user_id' => '392'),
            array('id' => '4','cyeo_name' => 'Brian Parsons','cyeo_sig' => NULL,'cyeo_address' => '31 Buckland Close','cyeo_city' => 'Peterborough','cyeo_state' => 'Cambridgeshire','cyeo_postcode' => 'PE3 9UH','cyeo_country' => 'U.K.','cyeo_htel' => '+44 1733 263211','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'gill.parsons@btinternet.com','application_no' => '2965','ribi_club_id' => NULL,'user_id' => '393'),
            array('id' => '5','cyeo_name' => "Collette O'Neill",'cyeo_sig' => NULL,'cyeo_address' => 'Cherry Grove, Model Farm Road','cyeo_city' => 'Cork','cyeo_state' => 'Cork','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '876175054','cyeo_fax' => '','cyeo_email' => 'colletteoneill24@gmail.com','application_no' => '3080','ribi_club_id' => NULL,'user_id' => '394'),
            array('id' => '6','cyeo_name' => 'John MacCrossan','cyeo_sig' => NULL,'cyeo_address' => '30 Gleneagles Culmore Rd ','cyeo_city' => 'Londonderry ','cyeo_state' => 'county Antrim','cyeo_postcode' => 'BT487TF','cyeo_country' => 'northern Ireland','cyeo_htel' => 'o2871354023','cyeo_wtel' => '','cyeo_mobile' => '7703499314','cyeo_fax' => '','cyeo_email' => 'johnmaccrossan@btinternet.com','application_no' => '3046','ribi_club_id' => NULL,'user_id' => '395'),
            array('id' => '7','cyeo_name' => "O'Fee James",'cyeo_sig' => NULL,'cyeo_address' => '11 Raglan Road','cyeo_city' => 'Bangor','cyeo_state' => 'County Down','cyeo_postcode' => 'BT20 3TL','cyeo_country' => 'Northern Ireland','cyeo_htel' => '+44289147 0232','cyeo_wtel' => '','cyeo_mobile' => '222','cyeo_fax' => NULL,'cyeo_email' => 'ofee59@yahoo.co.uk','application_no' => '2950','ribi_club_id' => '2','user_id' => '396'),
            array('id' => '9','cyeo_name' => 'Chris Warnock','cyeo_sig' => NULL,'cyeo_address' => '17My Ladys Mile Holywood','cyeo_city' => 'Holywood','cyeo_state' => 'County Down','cyeo_postcode' => 'BT18 9EW','cyeo_country' => 'northern Ireland','cyeo_htel' => '90425525','cyeo_wtel' => '','cyeo_mobile' => '7068842975','cyeo_fax' => NULL,'cyeo_email' => 'c.warnock@talk21.com','application_no' => '2979','ribi_club_id' => NULL,'user_id' => '397'),
            array('id' => '11','cyeo_name' => 'Seamus Devine ','cyeo_sig' => NULL,'cyeo_address' => 'Port Road ','cyeo_city' => 'Letterkenny','cyeo_state' => 'Donegal','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '749122775','cyeo_wtel' => '','cyeo_mobile' => '872482775','cyeo_fax' => '','cyeo_email' => 'seamus@stewartandmaclochlainn.ie','application_no' => '3012','ribi_club_id' => NULL,'user_id' => '398'),
            array('id' => '12','cyeo_name' => 'Cath Chorley','cyeo_sig' => NULL,'cyeo_address' => '8 the Spinneys','cyeo_city' => 'Dalgety Bay','cyeo_state' => 'Fife','cyeo_postcode' => 'KY11 9SL','cyeo_country' => 'UK','cyeo_htel' => '01383 823578','cyeo_wtel' => '01383 823578','cyeo_mobile' => '07976 888619','cyeo_fax' => '','cyeo_email' => 'cath.chorley@gmail.com','application_no' => '3097','ribi_club_id' => NULL,'user_id' => '399'),
            array('id' => '13','cyeo_name' => NULL,'cyeo_sig' => NULL,'cyeo_address' => NULL,'cyeo_city' => NULL,'cyeo_state' => NULL,'cyeo_postcode' => NULL,'cyeo_country' => NULL,'cyeo_htel' => NULL,'cyeo_wtel' => NULL,'cyeo_mobile' => NULL,'cyeo_fax' => NULL,'cyeo_email' => NULL,'application_no' => '3086','ribi_club_id' => NULL,'created_at' => NULL,'updated_at' => NULL,'user_id' => NULL),
            array('id' => '14','cyeo_name' => 'Colin Mason','cyeo_sig' => NULL,'cyeo_address' => '31 Allt-yr-yn Crescent','cyeo_city' => 'Newport ','cyeo_state' => '','cyeo_postcode' => ' NP20 5GE','cyeo_country' => 'Wales','cyeo_htel' => '1633267240','cyeo_wtel' => 'N/A','cyeo_mobile' => '7896993701','cyeo_fax' => 'N/A','cyeo_email' => 'colinmason222@googlemail.com','application_no' => '3005','ribi_club_id' => NULL,'user_id' => '400'),
            array('id' => '19','cyeo_name' => 'Sheena MacGillivray','cyeo_sig' => NULL,'cyeo_address' => '5 Sanquhar Drive','cyeo_city' => 'Forres','cyeo_state' => 'Fife','cyeo_postcode' => 'IV36 1DQ','cyeo_country' => 'UK','cyeo_htel' => '1309674947','cyeo_wtel' => '1309674947','cyeo_mobile' => '7742101239','cyeo_fax' => NULL,'cyeo_email' => 'sheenarotary@gmail.com','application_no' => '3063','ribi_club_id' => '89','user_id' => '401'),
            array('id' => '21','cyeo_name' => 'Hilary Hearnshaw','cyeo_sig' => NULL,'cyeo_address' => '74 Burnmill Road','cyeo_city' => 'Market Harborough','cyeo_state' => 'Leicestershire','cyeo_postcode' => 'LE16 7JG','cyeo_country' => 'U.K.','cyeo_htel' => '01858 469062','cyeo_wtel' => '','cyeo_mobile' => '07774 127005','cyeo_fax' => '','cyeo_email' => 'hilary.hearnshaw@warwick.ac.uk','application_no' => '2892','ribi_club_id' => NULL,'user_id' => '402'),
            array('id' => '26','cyeo_name' => 'Colin Yarwood','cyeo_sig' => NULL,'cyeo_address' => '38 The Rookery, Orton Wistow','cyeo_city' => 'Peterborough','cyeo_state' => 'Cambridgeshire','cyeo_postcode' => 'PE2 6YT','cyeo_country' => 'U.K.','cyeo_htel' => '01733 394669','cyeo_wtel' => '','cyeo_mobile' => '07763 774062','cyeo_fax' => '','cyeo_email' => 'colin.yarwood@gmail.com','application_no' => '2996','ribi_club_id' => NULL,'user_id' => '403'),
            array('id' => '29','cyeo_name' => 'Mikki Longley','cyeo_sig' => NULL,'cyeo_address' => '47 Gardiner Street','cyeo_city' => 'Market Harborough','cyeo_state' => 'Leicestershire','cyeo_postcode' => 'LE16 9QN','cyeo_country' => 'U.K.','cyeo_htel' => '+44 1858 468105','cyeo_wtel' => '','cyeo_mobile' => '+44 7738 273245','cyeo_fax' => '','cyeo_email' => 'mikki@mikkilongleycreative.com','application_no' => '3019','ribi_club_id' => NULL,'user_id' => '404'),
            array('id' => '32','cyeo_name' => 'Colin Jones','cyeo_sig' => NULL,'cyeo_address' => '11 Darren Close','cyeo_city' => 'Cowbridge','cyeo_state' => 'Vale of Glamorgan','cyeo_postcode' => 'CF71 7DE','cyeo_country' => 'Wales','cyeo_htel' => '1446774119','cyeo_wtel' => 'N/A','cyeo_mobile' => '7975614364','cyeo_fax' => 'N/A','cyeo_email' => 'colinj@cowbridge.co.uk','application_no' => '3074','ribi_club_id' => NULL,'user_id' => '405'),
            array('id' => '33','cyeo_name' => 'Ken Challenger','cyeo_sig' => NULL,'cyeo_address' => '186 Miller Way, Brampton','cyeo_city' => 'Huntingdon','cyeo_state' => 'Cambridgeshire','cyeo_postcode' => 'PE28 4UA','cyeo_country' => 'U.K.','cyeo_htel' => '01480 458212','cyeo_wtel' => '','cyeo_mobile' => '07778 839858','cyeo_fax' => '','cyeo_email' => 'kenchallenger@btinternet.com','application_no' => '2958','ribi_club_id' => NULL,'user_id' => '406'),
            array('id' => '34','cyeo_name' => 'margaret Bermingham','cyeo_sig' => NULL,'cyeo_address' => 'Breffni,Greenhill ','cyeo_city' => 'Fermoy ','cyeo_state' => 'Cork','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '2531118','cyeo_wtel' => '','cyeo_mobile' => '863527771','cyeo_fax' => '','cyeo_email' => 'margaretber@hotmail.com','application_no' => '3091','ribi_club_id' => NULL,'user_id' => '407'),
            array('id' => '35','cyeo_name' => 'Sheelagh O Shea','cyeo_sig' => NULL,'cyeo_address' => '7 Bearforest lower','cyeo_city' => 'Mallow','cyeo_state' => 'Cork','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '861040872','cyeo_fax' => '','cyeo_email' => 'sosweldon645@gmail.com','application_no' => '3106','ribi_club_id' => NULL,'user_id' => '408'),
            array('id' => '37','cyeo_name' => 'Paul Hughes ','cyeo_sig' => NULL,'cyeo_address' => '49 seven springs ','cyeo_city' => 'Newbridge','cyeo_state' => 'County Kildare ','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '','cyeo_wtel' => '35345449292','cyeo_mobile' => '876593857','cyeo_fax' => '','cyeo_email' => 'paul@newbridgetechnology.ie','application_no' => '2955','ribi_club_id' => NULL,'user_id' => '409'),
            array('id' => '38','cyeo_name' => 'Rod Tyler','cyeo_sig' => NULL,'cyeo_address' => '39 Belton Lane, Gt Gonerby','cyeo_city' => 'Grantham','cyeo_state' => 'Lincolnshire','cyeo_postcode' => 'NG31 8NB','cyeo_country' => 'U.K.','cyeo_htel' => '+44 1476 407002','cyeo_wtel' => '','cyeo_mobile' => '+44 7706 052397','cyeo_fax' => '','cyeo_email' => 'tylerrodney@hotmail.com','application_no' => '3009','ribi_club_id' => NULL,'user_id' => '410'),
            array('id' => '39','cyeo_name' => 'Valerie Smith ','cyeo_sig' => NULL,'cyeo_address' => 'Jew House Drove','cyeo_city' => 'Wisbech','cyeo_state' => 'Cambridgeshire','cyeo_postcode' => 'PE14 0NU','cyeo_country' => 'UK','cyeo_htel' => '1945860596','cyeo_wtel' => '','cyeo_mobile' => '7720274561','cyeo_fax' => '','cyeo_email' => 'valerie.j.smith@btinternet.com','application_no' => '2954','ribi_club_id' => NULL,'user_id' => '411'),
            array('id' => '41','cyeo_name' => 'Seamus Walsh','cyeo_sig' => NULL,'cyeo_address' => '14 Ardkeen Close','cyeo_city' => 'Dungannon','cyeo_state' => 'County Tyrone','cyeo_postcode' => 'BT71 6TP','cyeo_country' => 'Northern Ireland','cyeo_htel' => '4.42888E+12','cyeo_wtel' => '','cyeo_mobile' => '4.47717E+11','cyeo_fax' => '','cyeo_email' => 'seamus@walshs.org.uk','application_no' => '3077','ribi_club_id' => NULL,'user_id' => '412'),
            array('id' => '52','cyeo_name' => 'David Smith','cyeo_sig' => NULL,'cyeo_address' => '16 Goodens Lane, Great Doddington','cyeo_city' => 'Wellingborough','cyeo_state' => 'Northamptonshire','cyeo_postcode' => 'NN29 7TY','cyeo_country' => 'U.K.','cyeo_htel' => '+44 1933 274958','cyeo_wtel' => '','cyeo_mobile' => '+44 7976 422615','cyeo_fax' => '','cyeo_email' => 'davidsmith@dsagroup.co.uk','application_no' => '3134','ribi_club_id' => NULL,'user_id' => '413'),
            array('id' => '53','cyeo_name' => 'Philip Horwood','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '7785995450','cyeo_wtel' => '1758701701','cyeo_mobile' => '7785995450','cyeo_fax' => '','cyeo_email' => 'pohrotary@griffithwilliams.co.uk','application_no' => '2915','ribi_club_id' => NULL,'user_id' => '414'),
            array('id' => '54','cyeo_name' => 'Richard Meek','cyeo_sig' => NULL,'cyeo_address' => '4 Wentworth Close','cyeo_city' => 'Chippenham','cyeo_state' => 'Wiltshire','cyeo_postcode' => 'SN15 3XJ','cyeo_country' => 'UK','cyeo_htel' => '01249 655331','cyeo_wtel' => '','cyeo_mobile' => '07816 654784','cyeo_fax' => '','cyeo_email' => 'rankmeek@gmail.com','application_no' => '2629','ribi_club_id' => NULL,'user_id' => '415'),
            array('id' => '55','cyeo_name' => 'Joanne O Connor','cyeo_sig' => NULL,'cyeo_address' => 'AIB Bank,1 Custume  Place','cyeo_city' => 'Athlone','cyeo_state' => 'Westmeath','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '3.5386E+11','cyeo_fax' => '','cyeo_email' => 'joanneoc99@gmail.com','application_no' => '3129','ribi_club_id' => NULL,'user_id' => '416'),
            array('id' => '57','cyeo_name' => 'Andrew Page','cyeo_sig' => NULL,'cyeo_address' => '1 Fold Court, Chaddesley Corbett','cyeo_city' => 'Kidderminster','cyeo_state' => 'Worcs','cyeo_postcode' => 'DY10 4SA','cyeo_country' => 'UK','cyeo_htel' => '01562 777584','cyeo_wtel' => '','cyeo_mobile' => '07814 496879','cyeo_fax' => '','cyeo_email' => 'ajp584@gmail.com','application_no' => '3144','ribi_club_id' => NULL,'user_id' => '417'),
            array('id' => '60','cyeo_name' => 'Michael (Mike) Enderby','cyeo_sig' => NULL,'cyeo_address' => 'St Wendredas','cyeo_city' => 'March','cyeo_state' => 'Cambridgeshire','cyeo_postcode' => 'PE19 9QF','cyeo_country' => 'UK','cyeo_htel' => '01354 654760','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'mikeenderby@talktalk.net','application_no' => '2941','ribi_club_id' => NULL,'user_id' => '418'),
            array('id' => '67','cyeo_name' => 'Duncan Cassley','cyeo_sig' => NULL,'cyeo_address' => '75 Wordsworth Avenue','cyeo_city' => 'Straford on Avon','cyeo_state' => 'Warwickshire','cyeo_postcode' => 'CV37 7JB','cyeo_country' => 'UK','cyeo_htel' => '01789 266537','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'duncan cassley@sky.com','application_no' => '2887','ribi_club_id' => NULL,'user_id' => '419'),
            array('id' => '71','cyeo_name' => 'Jean Kibblewhite','cyeo_sig' => NULL,'cyeo_address' => 'Garnon Lines. Kendal Avenue','cyeo_city' => 'Epping','cyeo_state' => 'Essex','cyeo_postcode' => 'CM16 4PW','cyeo_country' => 'UK','cyeo_htel' => '01992 573828','cyeo_wtel' => '','cyeo_mobile' => '07759 668285','cyeo_fax' => '','cyeo_email' => 'jebk@hotmail.co.uk','application_no' => '3127','ribi_club_id' => NULL,'user_id' => '420'),
            array('id' => '81','cyeo_name' => 'Chris Mill','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'chriscmill@yahoo.co.uk','application_no' => '3010','ribi_club_id' => NULL,'user_id' => '421'),
            array('id' => '83','cyeo_name' => 'Pankaj Chahwala','cyeo_sig' => NULL,'cyeo_address' => '17 Donnington Road','cyeo_city' => 'Kenton','cyeo_state' => '','cyeo_postcode' => 'HA3 0NB','cyeo_country' => 'UK','cyeo_htel' => '020 31134030','cyeo_wtel' => '','cyeo_mobile' => '7878832970','cyeo_fax' => '','cyeo_email' => 'pankaj@aol.com','application_no' => '2908','ribi_club_id' => NULL,'user_id' => '422'),
            array('id' => '87','cyeo_name' => 'Dominik Wanner','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => 'UK','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '+44 7435 859448','cyeo_fax' => '','cyeo_email' => 'dominikwanner@hotmail.com','application_no' => '3140','ribi_club_id' => NULL,'user_id' => '424'),
            array('id' => '91','cyeo_name' => 'Alan Rice-Smith','cyeo_sig' => NULL,'cyeo_address' => '12 Santers Lane','cyeo_city' => 'Potters Bar','cyeo_state' => 'Hertfordshire','cyeo_postcode' => 'EN6 2BU','cyeo_country' => 'UK','cyeo_htel' => '+44 1707 650692','cyeo_wtel' => '','cyeo_mobile' => '+44 7900 227355','cyeo_fax' => '','cyeo_email' => 'alanrice-smith@hotmail.co.uk','application_no' => '2953','ribi_club_id' => NULL,'user_id' => '425'),
            array('id' => '95','cyeo_name' => 'Hugh Clatworthy','cyeo_sig' => NULL,'cyeo_address' => '3 Springfield Close','cyeo_city' => 'Newport','cyeo_state' => 'Gwent','cyeo_postcode' => 'NP10 8RZ','cyeo_country' => 'Wales','cyeo_htel' => '01633 893919','cyeo_wtel' => 'N/A','cyeo_mobile' => 'N/A','cyeo_fax' => 'N/A','cyeo_email' => 'Clatworthyhugh@aol.com','application_no' => '3221','ribi_club_id' => NULL,'user_id' => '426'),
            array('id' => '98','cyeo_name' => 'Alan Gabriel','cyeo_sig' => NULL,'cyeo_address' => '2 Waltham Close, Morriston','cyeo_city' => 'SWANSEA ','cyeo_state' => 'City and County of Swansea','cyeo_postcode' => 'SA6 7PH','cyeo_country' => 'Wales, UK','cyeo_htel' => ' 01792 774014','cyeo_wtel' => 'N/A','cyeo_mobile' => '07814 404399','cyeo_fax' => 'N/A','cyeo_email' => 'alan.gabriel2@btinternet.com','application_no' => '3219','ribi_club_id' => NULL,'user_id' => '427'),
            array('id' => '100','cyeo_name' => 'Paula Tayler','cyeo_sig' => NULL,'cyeo_address' => '54, Foxhall Road','cyeo_city' => 'DIDCOT','cyeo_state' => 'Oxon.','cyeo_postcode' => 'OX11 7AA','cyeo_country' => 'UK','cyeo_htel' => '+44 1235 813986','cyeo_wtel' => '','cyeo_mobile' => '+44 7899 953616','cyeo_fax' => '','cyeo_email' => 'p.tayler@hotmail.co.uk','application_no' => '3228','ribi_club_id' => NULL,'user_id' => '428'),
            array('id' => '101','cyeo_name' => 'Lance Slater','cyeo_sig' => NULL,'cyeo_address' => '31 Rookery Court','cyeo_city' => 'Marlow','cyeo_state' => 'Bucks.','cyeo_postcode' => 'SL7 3HR','cyeo_country' => 'UK','cyeo_htel' => '+44 1628 484323','cyeo_wtel' => '','cyeo_mobile' => '+44 7803 179911','cyeo_fax' => '','cyeo_email' => 'lms37@outlook.com','application_no' => '3236','ribi_club_id' => NULL,'user_id' => '429'),
            array('id' => '103','cyeo_name' => 'Paul Halstead','cyeo_sig' => NULL,'cyeo_address' => '2 Rowan Close','cyeo_city' => 'Penarth','cyeo_state' => 'Vale of Glamorgan','cyeo_postcode' => 'CF64 5BU','cyeo_country' => 'Wales','cyeo_htel' => ' 02920 705248','cyeo_wtel' => '','cyeo_mobile' => '0775 4154272','cyeo_fax' => '','cyeo_email' => 'barryrotaryclub@gmail.com','application_no' => '3245','ribi_club_id' => NULL,'user_id' => '430'),
            array('id' => '107','cyeo_name' => 'Alistair Mackintosh','cyeo_sig' => NULL,'cyeo_address' => '28 Greennlady Walk','cyeo_city' => 'Lanark','cyeo_state' => 'South Lanarkshire','cyeo_postcode' => 'ML11 7EP','cyeo_country' => 'Great Britain','cyeo_htel' => '01555-662223','cyeo_wtel' => '','cyeo_mobile' => '0795-643-8115','cyeo_fax' => '','cyeo_email' => 'ali.mack50@btinternet.com','application_no' => '3222','ribi_club_id' => NULL,'user_id' => '432'),
            array('id' => '121','cyeo_name' => 'Sandy Aked-Walker','cyeo_sig' => NULL,'cyeo_address' => 'Hill House, Holly Drive,Banbury Road','cyeo_city' => 'Litchborough','cyeo_state' => 'Northants','cyeo_postcode' => 'NN12 8JF','cyeo_country' => 'UK','cyeo_htel' => '+44 (0)1327830077','cyeo_wtel' => '','cyeo_mobile' => '+44 (0)7759326675','cyeo_fax' => '','cyeo_email' => 'dg2010@tiscali.co.uk','application_no' => '3260','ribi_club_id' => NULL,'user_id' => '433'),
            array('id' => '122','cyeo_name' => 'Di King','cyeo_sig' => NULL,'cyeo_address' => '49 Leinster Avenue','cyeo_city' => 'East Sheen','cyeo_state' => 'London','cyeo_postcode' => 'SW14 7JW','cyeo_country' => 'UK','cyeo_htel' => '+44(0) 20 8876 8997','cyeo_wtel' => '','cyeo_mobile' => '+(0) 7545575456','cyeo_fax' => '','cyeo_email' => 'di.londonyex@gmail.com','application_no' => '3242','ribi_club_id' => NULL,'user_id' => '434'),
            array('id' => '124','cyeo_name' => 'Jonathan Nish','cyeo_sig' => NULL,'cyeo_address' => '32 Teaseltun','cyeo_city' => 'Fleet','cyeo_state' => 'Hampshire','cyeo_postcode' => 'GU51 5BY','cyeo_country' => 'UK','cyeo_htel' => '+44(0)20 81234570','cyeo_wtel' => '','cyeo_mobile' => '+44(0)7789 434130','cyeo_fax' => '','cyeo_email' => 'secretary @putneyrotary.org.uk','application_no' => '3226','ribi_club_id' => NULL,'user_id' => '435'),
            array('id' => '130','cyeo_name' => 'Joyce Marston','cyeo_sig' => NULL,'cyeo_address' => '12 Seaton Road','cyeo_city' => 'Uppingham','cyeo_state' => 'Rutland','cyeo_postcode' => 'LE15 9QX','cyeo_country' => 'UK','cyeo_htel' => '+44 1572 822731','cyeo_wtel' => '','cyeo_mobile' => '+44 7855 315106','cyeo_fax' => '','cyeo_email' => 'joyce.marston21@gmail.com','application_no' => '3296','ribi_club_id' => NULL,'user_id' => '436'),
            array('id' => '150','cyeo_name' => 'David Dawkins','cyeo_sig' => NULL,'cyeo_address' => '27 Windmill Way, Middle Tysoe','cyeo_city' => 'Warwick','cyeo_state' => '','cyeo_postcode' => 'CV35 0SB','cyeo_country' => 'UK','cyeo_htel' => '01295 688234','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'daviddragonfly@ymail.com','application_no' => '3262','ribi_club_id' => NULL,'user_id' => '437'),
            array('id' => '152','cyeo_name' => 'Valerie Chodesh','cyeo_sig' => NULL,'cyeo_address' => '35 Chantry Lane','cyeo_city' => 'Hatfield','cyeo_state' => 'Herts','cyeo_postcode' => 'AL10 9HS','cyeo_country' => 'UK','cyeo_htel' => '','cyeo_wtel' => '1707881987','cyeo_mobile' => '7767373448','cyeo_fax' => '','cyeo_email' => 'val8cho@gmail.com','application_no' => '3310','ribi_club_id' => NULL,'user_id' => '438'),
            array('id' => '153','cyeo_name' => 'Colin Nicholls','cyeo_sig' => NULL,'cyeo_address' => 'Beaston Farm Rearour ,Nr Aherla','cyeo_city' => '','cyeo_state' => 'Cork ','cyeo_postcode' => '','cyeo_country' => 'Ireland ','cyeo_htel' => '3.53217E+11','cyeo_wtel' => '','cyeo_mobile' => '3.53874E+11','cyeo_fax' => '','cyeo_email' => 'candanicholls@gmail.com','application_no' => '3263','ribi_club_id' => NULL,'user_id' => '439'),
            array('id' => '157','cyeo_name' => 'Geoff Knights','cyeo_sig' => NULL,'cyeo_address' => '14 Harrington Walk','cyeo_city' => 'Lichfield','cyeo_state' => '','cyeo_postcode' => 'WS13 7UY','cyeo_country' => 'UK','cyeo_htel' => '01543 898455','cyeo_wtel' => '','cyeo_mobile' => '07435 566969','cyeo_fax' => '','cyeo_email' => 'geoffknights@yahoo.com','application_no' => '3227','ribi_club_id' => NULL,'user_id' => '440'),
            array('id' => '161','cyeo_name' => 'Pat McNulty','cyeo_sig' => NULL,'cyeo_address' => 'Lorien,Tully,Strandhill,','cyeo_city' => 'Sligo ','cyeo_state' => 'Sligo','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '3.53719E+11','cyeo_wtel' => '','cyeo_mobile' => '3.53879E+11','cyeo_fax' => '','cyeo_email' => 'patbmcnulty@gmail.com','application_no' => '3323','ribi_club_id' => NULL,'user_id' => '441'),
            array('id' => '180','cyeo_name' => 'Roger Howells','cyeo_sig' => NULL,'cyeo_address' => 'Broadoaks, Lower Freystrop','cyeo_city' => 'Haverfordwest','cyeo_state' => ' Pembrokeshire','cyeo_postcode' => 'SA62 4ET','cyeo_country' => 'Wales','cyeo_htel' => '01437 760708','cyeo_wtel' => '','cyeo_mobile' => '07971 210229','cyeo_fax' => '','cyeo_email' => 'rogerrotary@tesco.net','application_no' => '3338','ribi_club_id' => NULL,'user_id' => '442'),
            array('id' => '187','cyeo_name' => 'Helen Wates','cyeo_sig' => NULL,'cyeo_address' => '172 Village Way','cyeo_city' => 'Beckenham','cyeo_state' => '','cyeo_postcode' => 'BR3 3PJ','cyeo_country' => 'UK','cyeo_htel' => '020 8650 1873','cyeo_wtel' => '','cyeo_mobile' => '7870492091','cyeo_fax' => '','cyeo_email' => 'b.wates@btinternet.com','application_no' => '3360','ribi_club_id' => NULL,'user_id' => '443'),
            array('id' => '188','cyeo_name' => 'Brian Taylor','cyeo_sig' => NULL,'cyeo_address' => 'Cavourne Firs Road ','cyeo_city' => 'Kenley','cyeo_state' => 'Surrey','cyeo_postcode' => 'CR8 5LG','cyeo_country' => 'United Kingdom','cyeo_htel' => '0208 668 8330','cyeo_wtel' => '','cyeo_mobile' => '07711 404312','cyeo_fax' => '','cyeo_email' => 'brian.taylor307@btinternet.com','application_no' => '3369','ribi_club_id' => NULL,'user_id' => '444'),
            array('id' => '196','cyeo_name' => 'Crosby McVeigh','cyeo_sig' => NULL,'cyeo_address' => '68 Newtownards Rd,','cyeo_city' => 'Comber Newtownards','cyeo_state' => 'Co Down','cyeo_postcode' => 'BT235LB','cyeo_country' => 'Northern  Ireland','cyeo_htel' => '4.42892E+11','cyeo_wtel' => '','cyeo_mobile' => '4.42892E+11','cyeo_fax' => '','cyeo_email' => 'crosbymcveigh@btinternet.com','application_no' => '3312','ribi_club_id' => NULL,'user_id' => '445'),
            array('id' => '214','cyeo_name' => 'John Smith','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'Forgeronfp@aol.com','application_no' => '3456','ribi_club_id' => NULL,'user_id' => '446'),
            array('id' => '220','cyeo_name' => 'John Hammond','cyeo_sig' => NULL,'cyeo_address' => '7 Pond Lane','cyeo_city' => 'Baldock','cyeo_state' => 'Hertfordshire','cyeo_postcode' => 'SG7 5AS','cyeo_country' => 'UK','cyeo_htel' => '+44 1462 894603','cyeo_wtel' => 'Not Applicable','cyeo_mobile' => '+44 7940 548220','cyeo_fax' => '','cyeo_email' => 'john.hammond1@btinternet.com','application_no' => '3442','ribi_club_id' => NULL,'user_id' => '447'),
            array('id' => '223','cyeo_name' => 'Tony Fundell','cyeo_sig' => NULL,'cyeo_address' => '63 South Rise','cyeo_city' => 'Llanishen','cyeo_state' => 'Cardiff','cyeo_postcode' => 'CF14 0RG','cyeo_country' => 'Wales','cyeo_htel' => '2920750335','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'afundell@btinternet.com','application_no' => '3451','ribi_club_id' => NULL,'user_id' => '448'),
            array('id' => '226','cyeo_name' => 'Roger Howells','cyeo_sig' => NULL,'cyeo_address' => 'Broadoaks, Lower Freystrop','cyeo_city' => 'Haverfordwest','cyeo_state' => 'Pembrokeshire','cyeo_postcode' => 'SA62 4ET','cyeo_country' => 'Wales','cyeo_htel' => '01437 760708','cyeo_wtel' => '','cyeo_mobile' => '7971210229','cyeo_fax' => '','cyeo_email' => 'rogerrotary1@gmail.com','application_no' => '3492','ribi_club_id' => NULL,'user_id' => '449'),
            array('id' => '234','cyeo_name' => 'Nigel Randall','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'oaktree.cottage@btinternet.com','application_no' => '3435','ribi_club_id' => NULL,'user_id' => '450'),
            array('id' => '235','cyeo_name' => 'Mike Ware','cyeo_sig' => NULL,'cyeo_address' => '7 Evenlode Road','cyeo_city' => 'Bourne End','cyeo_state' => 'Bucks.','cyeo_postcode' => 'SL8 5ND','cyeo_country' => 'UK','cyeo_htel' => '+44 1628 524559','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'waremike@talk21.com','application_no' => '3508','ribi_club_id' => NULL,'user_id' => '451'),
            array('id' => '238','cyeo_name' => 'Doug McArthur','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '01873 858726','cyeo_wtel' => '','cyeo_mobile' => '01873 858726','cyeo_fax' => '','cyeo_email' => 'dougmca@rocketmail.com','application_no' => '3524','ribi_club_id' => NULL,'user_id' => '452'),
            array('id' => '245','cyeo_name' => 'Peter Start','cyeo_sig' => NULL,'cyeo_address' => '29 Stonegate, Cowbit','cyeo_city' => 'Spalding','cyeo_state' => 'Lincolnshire','cyeo_postcode' => 'PE12 6AH','cyeo_country' => 'UK','cyeo_htel' => '+44 1406 380599','cyeo_wtel' => '','cyeo_mobile' => '+44 7958 592334','cyeo_fax' => '','cyeo_email' => 'peter.start@uwclub.net','application_no' => '3498','ribi_club_id' => NULL,'user_id' => '453'),
            array('id' => '249','cyeo_name' => 'Shaun Green','cyeo_sig' => NULL,'cyeo_address' => '5 Tower Close','cyeo_city' => 'Ramsey','cyeo_state' => 'Cambridgeshire','cyeo_postcode' => 'PE26 1BX','cyeo_country' => 'UK','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '+44 7766 695811','cyeo_fax' => '','cyeo_email' => 'Shaun.green@ramseyrotary.co.uk','application_no' => '3546','ribi_club_id' => NULL,'user_id' => '454'),
            array('id' => '254','cyeo_name' => 'Louis Boyle','cyeo_sig' => NULL,'cyeo_address' => '29 Jubilee Rd,','cyeo_city' => 'Dromore','cyeo_state' => 'County Down','cyeo_postcode' => 'BT251QH','cyeo_country' => 'Northern Ireland','cyeo_htel' => '4.42893E+11','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'louisboyle@btinternet.com','application_no' => '3491','ribi_club_id' => NULL,'user_id' => '455'),
            array('id' => '262','cyeo_name' => 'Eoin McConville','cyeo_sig' => NULL,'cyeo_address' => '39 Camlough Rd, ','cyeo_city' => 'Newry ','cyeo_state' => 'County Down','cyeo_postcode' => 'BT357LS','cyeo_country' => 'Northern Ireland','cyeo_htel' => '4.4283E+11','cyeo_wtel' => '','cyeo_mobile' => '4.47842E+11','cyeo_fax' => '','cyeo_email' => 'eoin.mcconville@ffsolicitors.com','application_no' => '3486','ribi_club_id' => NULL,'user_id' => '456'),
            array('id' => '268','cyeo_name' => 'Peter Taylor','cyeo_sig' => NULL,'cyeo_address' => 'HILLCROFT, Otter Close','cyeo_city' => 'Tipton St John','cyeo_state' => 'Devon','cyeo_postcode' => 'EX10 0J','cyeo_country' => 'UK','cyeo_htel' => '01404 811742','cyeo_wtel' => '','cyeo_mobile' => '07855 820940','cyeo_fax' => '','cyeo_email' => 'Peterjstay@gmail.com','application_no' => '3536','ribi_club_id' => NULL,'user_id' => '457'),
            array('id' => '269','cyeo_name' => 'Jane Grant','cyeo_sig' => NULL,'cyeo_address' => '46 Highfield Road, Oundle','cyeo_city' => 'Peterborough','cyeo_state' => 'Northamptonshire','cyeo_postcode' => 'PE8 4QP','cyeo_country' => 'UK','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '+44 7712 933574','cyeo_fax' => '','cyeo_email' => 'oundlerotary@gmail.com','application_no' => '3610','ribi_club_id' => NULL,'user_id' => '458'),
            array('id' => '271','cyeo_name' => 'Terry Holland','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'terryrdholland@btinternet.com','application_no' => '3599','ribi_club_id' => NULL,'user_id' => '459'),
            array('id' => '277','cyeo_name' => 'Richard Hughes','cyeo_sig' => NULL,'cyeo_address' => 'Plas Medi, Talley','cyeo_city' => 'Nr Llandeilo','cyeo_state' => 'Carmarthenshire','cyeo_postcode' => 'SA19 7YH','cyeo_country' => 'Wales','cyeo_htel' => '+44 1558 685710','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'jhughes19@btinternet.com','application_no' => '3578','ribi_club_id' => NULL,'user_id' => '460'),
            array('id' => '278','cyeo_name' => 'Cathy Ryan','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => 'Southwold','cyeo_state' => 'Suffolk','cyeo_postcode' => '','cyeo_country' => 'UK','cyeo_htel' => '1502723253','cyeo_wtel' => '','cyeo_mobile' => '7879996992','cyeo_fax' => '','cyeo_email' => 'cathy.ryan57@gmail.com','application_no' => '3434','ribi_club_id' => NULL,'user_id' => '461'),
            array('id' => '280','cyeo_name' => 'Bill Redmayne','cyeo_sig' => NULL,'cyeo_address' => '23 North Brink','cyeo_city' => 'Wisbech','cyeo_state' => 'Cambridgeshire','cyeo_postcode' => 'PE13 1JR','cyeo_country' => 'UK','cyeo_htel' => '7831838075','cyeo_wtel' => '','cyeo_mobile' => '7831838075','cyeo_fax' => '','cyeo_email' => 'whr-dg1080-0506@btconnect.com','application_no' => '3533','ribi_club_id' => NULL,'user_id' => '462'),
            array('id' => '281','cyeo_name' => 'Iain Sutherland','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => 'Soham','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '1353624353','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'iainmsutherland@aol.com','application_no' => '3448','ribi_club_id' => NULL,'user_id' => '463'),
            array('id' => '282','cyeo_name' => 'Patricia McNulty ','cyeo_sig' => NULL,'cyeo_address' => 'Lorien Tully, Strandhill','cyeo_city' => 'Sligo','cyeo_state' => 'county Sligo','cyeo_postcode' => '','cyeo_country' => 'Ireland ','cyeo_htel' => '3.53719E+11','cyeo_wtel' => '','cyeo_mobile' => '3.53879E+11','cyeo_fax' => '','cyeo_email' => 'patbmenulty@gmail.com','application_no' => '3619','ribi_club_id' => NULL,'user_id' => '464'),
            array('id' => '287','cyeo_name' => 'Di King','cyeo_sig' => NULL,'cyeo_address' => '49 Leinster Avenue','cyeo_city' => 'East Sheen','cyeo_state' => 'London','cyeo_postcode' => 'SW14 7JW','cyeo_country' => 'UK','cyeo_htel' => '020 8876 8997','cyeo_wtel' => '','cyeo_mobile' => '7545575456','cyeo_fax' => '','cyeo_email' => 'di.londonyex@gmail..con','application_no' => '3439','ribi_club_id' => NULL,'user_id' => '465'),
            array('id' => '290','cyeo_name' => 'Jonathan Nish','cyeo_sig' => NULL,'cyeo_address' => '32 Teaseltun','cyeo_city' => 'Fleet','cyeo_state' => 'Hampshire','cyeo_postcode' => 'GU51 5BY','cyeo_country' => 'UK','cyeo_htel' => '+44(0)208123 4570','cyeo_wtel' => '','cyeo_mobile' => '+(0)7789 434130','cyeo_fax' => '','cyeo_email' => 'secretary@putneyrotary.org.uk','application_no' => '3602','ribi_club_id' => NULL,'user_id' => '466'),
            array('id' => '292','cyeo_name' => 'Cristina Pin ','cyeo_sig' => NULL,'cyeo_address' => '11 Hornton Street ','cyeo_city' => 'London','cyeo_state' => '','cyeo_postcode' => 'W8 7NP','cyeo_country' => 'UK','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '7979682645','cyeo_fax' => '','cyeo_email' => 'cristinap249@gmail.com','application_no' => '3473','ribi_club_id' => NULL,'user_id' => '467'),
            array('id' => '303','cyeo_name' => 'Maeve Giltinane ','cyeo_sig' => NULL,'cyeo_address' => '86 Cranford Court ,Donnybrook','cyeo_city' => 'Dublin 4','cyeo_state' => '  ','cyeo_postcode' => '','cyeo_country' => 'Ireland ','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '3.53876E+11','cyeo_fax' => '','cyeo_email' => 'maeve_giltinane@hotmail.com','application_no' => '3594','ribi_club_id' => NULL,'user_id' => '468'),
            array('id' => '305','cyeo_name' => 'Christine Cockell','cyeo_sig' => NULL,'cyeo_address' => '17 Windmill Way','cyeo_city' => 'Tysoe','cyeo_state' => '','cyeo_postcode' => 'CV35 0SB','cyeo_country' => 'UK','cyeo_htel' => '01295 688233','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'c.cockell@btinternet.com','application_no' => '3601','ribi_club_id' => NULL,'user_id' => '469'),
            array('id' => '307','cyeo_name' => 'Elaine Habesch','cyeo_sig' => NULL,'cyeo_address' => '9 Vespan Road','cyeo_city' => 'London','cyeo_state' => '','cyeo_postcode' => 'W12 9QG','cyeo_country' => 'UK','cyeo_htel' => '2087491095','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'ehabesch@hotmail.co.uk','application_no' => '3629','ribi_club_id' => NULL,'user_id' => '470'),
            array('id' => '308','cyeo_name' => 'Liz Walton','cyeo_sig' => NULL,'cyeo_address' => '7 Mervyn Road','cyeo_city' => 'West Ealing','cyeo_state' => 'London','cyeo_postcode' => 'W13 9UW','cyeo_country' => 'UK','cyeo_htel' => '020 8840 6994','cyeo_wtel' => '','cyeo_mobile' => '7778434755','cyeo_fax' => '','cyeo_email' => 'bilizwal@aol.com','application_no' => '3627','ribi_club_id' => NULL,'user_id' => '471'),
            array('id' => '323','cyeo_name' => 'Sue Hutton','cyeo_sig' => NULL,'cyeo_address' => 'West Down. Down Park Drive','cyeo_city' => 'Tavistock','cyeo_state' => 'Devon','cyeo_postcode' => 'PL19 9AH','cyeo_country' => 'UK','cyeo_htel' => '01822 619608','cyeo_wtel' => '','cyeo_mobile' => '07860 373336','cyeo_fax' => '','cyeo_email' => 'Suehutton1@gmail.com','application_no' => '3618','ribi_club_id' => NULL,'user_id' => '472'),
            array('id' => '328','cyeo_name' => 'Mike Pepper','cyeo_sig' => NULL,'cyeo_address' => 'Yllys, Bellan School Lane','cyeo_city' => 'Powys','cyeo_state' => 'Welshpool','cyeo_postcode' => 'SY218SF','cyeo_country' => 'Wales','cyeo_htel' => '01938-552306','cyeo_wtel' => '','cyeo_mobile' => '07970-41123','cyeo_fax' => '','cyeo_email' => 'pepperyau@yahoo.co.uk','application_no' => '3668','ribi_club_id' => NULL,'user_id' => '473'),
            array('id' => '333','cyeo_name' => 'Colin Craig','cyeo_sig' => NULL,'cyeo_address' => 'the farr end, culduthel rd','cyeo_city' => 'inverness','cyeo_state' => '','cyeo_postcode' => 'IV2 4BH','cyeo_country' => 'UK','cyeo_htel' => '01463 714173','cyeo_wtel' => '01463 242383','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'colin@highlandpropertysearch.co.uk','application_no' => '3685','ribi_club_id' => NULL,'user_id' => '474'),
            array('id' => '334','cyeo_name' => 'Paul Mapletoft','cyeo_sig' => NULL,'cyeo_address' => '3 Rushington Avenue','cyeo_city' => 'Maidenhead','cyeo_state' => 'Berkshire','cyeo_postcode' => 'SL6 1BY','cyeo_country' => 'UK','cyeo_htel' => '+44 1628 773229','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'paulandkimerie@aol.com','application_no' => '3704','ribi_club_id' => NULL,'user_id' => '475'),
            array('id' => '341','cyeo_name' => 'Hugh Clatworthy','cyeo_sig' => NULL,'cyeo_address' => '3 Springfield Close','cyeo_city' => 'Newport','cyeo_state' => 'Gwent','cyeo_postcode' => 'NP10 8RZ','cyeo_country' => 'Wales','cyeo_htel' => '01633 893919','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'clatworthyhugh@gmail.com','application_no' => '3731','ribi_club_id' => NULL,'user_id' => '476'),
            array('id' => '342','cyeo_name' => 'Peter Oeppen','cyeo_sig' => NULL,'cyeo_address' => ' 4 Marylands,Penally','cyeo_city' => 'Tenby','cyeo_state' => 'Pembrokeshire','cyeo_postcode' => 'SA70 7QF','cyeo_country' => 'Wales','cyeo_htel' => '01834 845681 ','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'peteroeppen@impactpoint.co.uk','application_no' => '3728','ribi_club_id' => NULL,'user_id' => '477'),
            array('id' => '344','cyeo_name' => 'Alison Thomas','cyeo_sig' => NULL,'cyeo_address' => ' 12 Sanderling Way','cyeo_city' => 'Porthcawl','cyeo_state' => 'Bridgend County Borough','cyeo_postcode' => 'CF36 3TD','cyeo_country' => '','cyeo_htel' => '01656 222985','cyeo_wtel' => '','cyeo_mobile' => '7581048448','cyeo_fax' => '','cyeo_email' => 'alisonmeredithjones@yahoo.com','application_no' => '3721','ribi_club_id' => NULL,'user_id' => '478'),
            array('id' => '345','cyeo_name' => 'Gareth Rees','cyeo_sig' => NULL,'cyeo_address' => ' The Stables, Dimlands Road','cyeo_city' => 'Llantwit Major','cyeo_state' => 'Vale of Glamorgan','cyeo_postcode' => 'CF61 1YX','cyeo_country' => 'Wales','cyeo_htel' => '01446 793399','cyeo_wtel' => '','cyeo_mobile' => '7791551928','cyeo_fax' => '','cyeo_email' => ' gareth.rees26@btinternet.com','application_no' => '3720','ribi_club_id' => NULL,'user_id' => '479'),
            array('id' => '346','cyeo_name' => 'Talfyn Harries','cyeo_sig' => NULL,'cyeo_address' => '17 Celtic Road, Garth','cyeo_city' => 'Maesteg','cyeo_state' => 'Mid Glam','cyeo_postcode' => 'CF34 0YJ','cyeo_country' => 'Wales','cyeo_htel' => '01656 711078','cyeo_wtel' => '','cyeo_mobile' => '7999886142','cyeo_fax' => '','cyeo_email' => 'talfynharries@sky.com','application_no' => '3762','ribi_club_id' => NULL,'user_id' => '480'),
            array('id' => '351','cyeo_name' => 'John Hawkins','cyeo_sig' => NULL,'cyeo_address' => '59 High Street, St. Martins','cyeo_city' => 'Stamford','cyeo_state' => 'Lincs','cyeo_postcode' => 'PE9 2LA','cyeo_country' => 'UK','cyeo_htel' => '+44 1780 763133','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'jfhawk@tiscali.co.uk','application_no' => '3746','ribi_club_id' => NULL,'user_id' => '481'),
            array('id' => '352','cyeo_name' => 'Brian Parsons','cyeo_sig' => NULL,'cyeo_address' => '31 Buckland Close','cyeo_city' => 'Peterborough','cyeo_state' => 'Cambs','cyeo_postcode' => 'PE3 9UH','cyeo_country' => 'UK','cyeo_htel' => '+44 1733 263211','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'gill_parsons@btinternet.com','application_no' => '3779','ribi_club_id' => NULL,'user_id' => '482'),
            array('id' => '353','cyeo_name' => 'Nick Abell','cyeo_sig' => NULL,'cyeo_address' => '5 Orchard Close, Hail Weston','cyeo_city' => 'St Neots','cyeo_state' => 'Cambs','cyeo_postcode' => 'PE19 5LF','cyeo_country' => 'UK','cyeo_htel' => '+44 1480 215880','cyeo_wtel' => '','cyeo_mobile' => '+44 7845 931700','cyeo_fax' => '','cyeo_email' => 'nickabell764@gmail.com','application_no' => '3783','ribi_club_id' => NULL,'user_id' => '483'),
            array('id' => '358','cyeo_name' => 'Sheila Cookson','cyeo_sig' => NULL,'cyeo_address' => '36 Highclere','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => 'DY12 2EY','cyeo_country' => 'UK','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '7376417330','cyeo_fax' => '','cyeo_email' => 'sheila@cheshireslasermail.co.uk','application_no' => '3739','ribi_club_id' => NULL,'user_id' => '484'),
            array('id' => '363','cyeo_name' => 'Gina Randall','cyeo_sig' => NULL,'cyeo_address' => '15 Abbey Fields','cyeo_city' => 'Ramsey','cyeo_state' => 'Cambs','cyeo_postcode' => 'PE26 1TG','cyeo_country' => 'UK','cyeo_htel' => '+44 1487 711079','cyeo_wtel' => '','cyeo_mobile' => '+44 7711 721120','cyeo_fax' => '','cyeo_email' => 'youth@ramseyrotary.co.uk','application_no' => '3809','ribi_club_id' => NULL,'user_id' => '485'),
            array('id' => '364','cyeo_name' => 'Richard Wells','cyeo_sig' => NULL,'cyeo_address' => '41 Station Road, Morton','cyeo_city' => 'Bourne','cyeo_state' => 'Lincs','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '+44 1778 570370','cyeo_wtel' => '','cyeo_mobile' => '+44 7740 026189','cyeo_fax' => '','cyeo_email' => 'rexcons@aol.com','application_no' => '3795','ribi_club_id' => NULL,'user_id' => '486'),
            array('id' => '372','cyeo_name' => 'Mark Alderman','cyeo_sig' => NULL,'cyeo_address' => '58 St Botolphs Road, Barton Seagrave','cyeo_city' => 'Kettering','cyeo_state' => 'Northants','cyeo_postcode' => 'NN15 6SS','cyeo_country' => 'UK','cyeo_htel' => '+44 1536 514413','cyeo_wtel' => '','cyeo_mobile' => '+44 7715 369450','cyeo_fax' => '','cyeo_email' => 'aldies@btinternet.com','application_no' => '3766','ribi_club_id' => NULL,'user_id' => '487'),
            array('id' => '375','cyeo_name' => 'Colin Yarwood','cyeo_sig' => NULL,'cyeo_address' => '38 The Rookery, Orton Wistow','cyeo_city' => 'Peterborough','cyeo_state' => 'Cambs','cyeo_postcode' => 'PE2 6YT','cyeo_country' => 'UK','cyeo_htel' => '+44 1733 394669','cyeo_wtel' => '','cyeo_mobile' => '+44 7763 774062','cyeo_fax' => '','cyeo_email' => 'rtncoliny@icloud.com','application_no' => '3787','ribi_club_id' => NULL,'user_id' => '488'),
            array('id' => '378','cyeo_name' => 'Peter Dowse','cyeo_sig' => NULL,'cyeo_address' => '14 Stocksfield, Kelvedon Hatch','cyeo_city' => 'Brentwood','cyeo_state' => 'Essex','cyeo_postcode' => 'CM15 0BU','cyeo_country' => 'England','cyeo_htel' => '01277 374342','cyeo_wtel' => '','cyeo_mobile' => '7957562678','cyeo_fax' => '','cyeo_email' => 'peterdowse69@gmail.com','application_no' => '3817','ribi_club_id' => NULL,'user_id' => '489'),
            array('id' => '384','cyeo_name' => 'Janet Martin','cyeo_sig' => NULL,'cyeo_address' => '48 Lawn Ave','cyeo_city' => 'Peterborough','cyeo_state' => 'Cambs','cyeo_postcode' => 'PE1 3RB','cyeo_country' => 'UK','cyeo_htel' => '+44 1733 314403','cyeo_wtel' => '','cyeo_mobile' => '+44 7804 917496','cyeo_fax' => '','cyeo_email' => 'janet.kitchen@outlook.com','application_no' => '3799','ribi_club_id' => NULL,'user_id' => '490'),
            array('id' => '391','cyeo_name' => 'Jenny Spratt','cyeo_sig' => NULL,'cyeo_address' => '5 Barn Owl Close, Langtoft','cyeo_city' => 'Peterborough','cyeo_state' => 'Cambs','cyeo_postcode' => 'PE6 9RG','cyeo_country' => 'UK','cyeo_htel' => '+44 1778 345736','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'jennyspratt@btinternet.com','application_no' => '3816','ribi_club_id' => NULL,'user_id' => '491'),
            array('id' => '397','cyeo_name' => 'Sarah Broom','cyeo_sig' => NULL,'cyeo_address' => '22 Redebourn Lane','cyeo_city' => 'Bury, Ramsey','cyeo_state' => 'Cambs','cyeo_postcode' => 'PE26 2PB','cyeo_country' => 'UK','cyeo_htel' => '+44 1487 815998','cyeo_wtel' => '','cyeo_mobile' => '+44 7710 571018','cyeo_fax' => '','cyeo_email' => 'sarahbroom@ramseyrotary.co.uk','application_no' => '3774','ribi_club_id' => NULL,'user_id' => '492'),
            array('id' => '400','cyeo_name' => 'Eimear McAuliffe','cyeo_sig' => NULL,'cyeo_address' => '31 Cabinteely Ave, Cabinteely','cyeo_city' => 'Dublin18','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '35312854414','cyeo_wtel' => '','cyeo_mobile' => '3.53877E+11','cyeo_fax' => '','cyeo_email' => 'eimear.mcauliffe@gmail.com','application_no' => '3818','ribi_club_id' => NULL,'user_id' => '493'),
            array('id' => '406','cyeo_name' => 'Tom Mulligan ','cyeo_sig' => NULL,'cyeo_address' => '6 Beechlawn Drive ,Monksland ','cyeo_city' => 'Athlone ','cyeo_state' => 'Roscommon ','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '3.53906E+11','cyeo_wtel' => '','cyeo_mobile' => '3.53868E+11','cyeo_fax' => '','cyeo_email' => 'tommull1@eircom.net ','application_no' => '3752','ribi_club_id' => NULL,'user_id' => '494'),
            array('id' => '409','cyeo_name' => 'Martin Horsted','cyeo_sig' => NULL,'cyeo_address' => 'Springfield Cottage, Asheridge','cyeo_city' => 'Chesham','cyeo_state' => 'Bucks','cyeo_postcode' => 'HP5 2UU','cyeo_country' => 'UK','cyeo_htel' => '01494 757284','cyeo_wtel' => '','cyeo_mobile' => '7506464788','cyeo_fax' => '','cyeo_email' => 'martin.horsted@icloud.com','application_no' => '3751','ribi_club_id' => NULL,'user_id' => '495'),
            array('id' => '413','cyeo_name' => 'Peter King','cyeo_sig' => NULL,'cyeo_address' => '49 Leinster Ave','cyeo_city' => 'East Sheen','cyeo_state' => 'London','cyeo_postcode' => 'SW14 7JW','cyeo_country' => 'United Kingdom','cyeo_htel' => '2088768997','cyeo_wtel' => '','cyeo_mobile' => '7973147118','cyeo_fax' => '','cyeo_email' => 'kingpd@hotmail.com','application_no' => '3797','ribi_club_id' => NULL,'user_id' => '496'),
            array('id' => '420','cyeo_name' => 'Glenda Groome','cyeo_sig' => NULL,'cyeo_address' => 'Kilcumney House, South Green St,','cyeo_city' => 'Kildare','cyeo_state' => 'Co Kildare','cyeo_postcode' => '','cyeo_country' => 'Ireland ','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '3.53872E+11','cyeo_fax' => '','cyeo_email' => 'glendagroome@cpckilcullen.com','application_no' => '3849','ribi_club_id' => NULL,'user_id' => '497'),
            array('id' => '422','cyeo_name' => 'Neil Kelly','cyeo_sig' => NULL,'cyeo_address' => '234 Charlesland Park,Greystones','cyeo_city' => '','cyeo_state' => 'Co Wicklow','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '3.53869E+11','cyeo_fax' => '','cyeo_email' => 'mr.neil.kelly@gmail.com','application_no' => '3729','ribi_club_id' => NULL,'user_id' => '498'),
            array('id' => '426','cyeo_name' => 'John Bash','cyeo_sig' => NULL,'cyeo_address' => '14 Lyndale Avenue','cyeo_city' => 'London ','cyeo_state' => '','cyeo_postcode' => 'NW2 2OY','cyeo_country' => 'UK','cyeo_htel' => '020 7435 3367','cyeo_wtel' => '','cyeo_mobile' => '07989 034118','cyeo_fax' => '','cyeo_email' => 'john@childshill.net','application_no' => '3852','ribi_club_id' => NULL,'user_id' => '499'),
            array('id' => '428','cyeo_name' => 'Asha Sharma','cyeo_sig' => NULL,'cyeo_address' => '15 Moriarty Close','cyeo_city' => 'London ','cyeo_state' => '','cyeo_postcode' => 'N7 0EF','cyeo_country' => 'UK','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '07841 967704','cyeo_fax' => '','cyeo_email' => 'sharma1aad@gmail.com','application_no' => '3865','ribi_club_id' => NULL,'user_id' => '500'),
            array('id' => '429','cyeo_name' => 'Shirley Kirk','cyeo_sig' => NULL,'cyeo_address' => '15 Lovett Road','cyeo_city' => 'Harefield','cyeo_state' => '','cyeo_postcode' => 'UB9 6 DN','cyeo_country' => 'UK','cyeo_htel' => '01895 821858','cyeo_wtel' => '','cyeo_mobile' => '07966 131722','cyeo_fax' => '','cyeo_email' => 'shirleykirk0@gmail.com','application_no' => '3867','ribi_club_id' => NULL,'user_id' => '501'),
            array('id' => '434','cyeo_name' => 'Gavin Westley ','cyeo_sig' => NULL,'cyeo_address' => 'currymount ','cyeo_city' => 'Buttevant ','cyeo_state' => 'County cork','cyeo_postcode' => '','cyeo_country' => 'Ireland','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '3.53873E+11','cyeo_fax' => '','cyeo_email' => 'gavin.westley@hobartltd.com','application_no' => '3857','ribi_club_id' => NULL,'user_id' => '502'),
            array('id' => '439','cyeo_name' => 'Ian Taylor','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'mitaylor@live.com','application_no' => '3856','ribi_club_id' => NULL,'user_id' => '503'),
            array('id' => '441','cyeo_name' => 'Ron Pearce','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '07703 567982','cyeo_fax' => '','cyeo_email' => 'rpbromsgrove999@aol.com','application_no' => '3908','ribi_club_id' => NULL,'user_id' => '504'),
            array('id' => '443','cyeo_name' => 'Karen Brimson','cyeo_sig' => NULL,'cyeo_address' => '6 Sunningdale Road','cyeo_city' => 'Chelmsford','cyeo_state' => 'Essex','cyeo_postcode' => 'CM1 2NH','cyeo_country' => 'UK','cyeo_htel' => '07880 791997','cyeo_wtel' => '','cyeo_mobile' => '07880 791997','cyeo_fax' => '','cyeo_email' => 'karenbrimson@hotmail.co.uk','application_no' => '3916','ribi_club_id' => NULL,'user_id' => '505'),
            array('id' => '445','cyeo_name' => 'Gilly Rushton','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '','cyeo_wtel' => '','cyeo_mobile' => '07831 633495','cyeo_fax' => '','cyeo_email' => 'gillyrushton@gmail.com','application_no' => '3820','ribi_club_id' => NULL,'user_id' => '506'),
            array('id' => '446','cyeo_name' => 'Louise McCance-Price','cyeo_sig' => NULL,'cyeo_address' => 'Flat 6/  25 Chartfield Avenue','cyeo_city' => 'Putney','cyeo_state' => 'London','cyeo_postcode' => 'SW15 6DZ','cyeo_country' => 'UK','cyeo_htel' => '07789 510297','cyeo_wtel' => '','cyeo_mobile' => '07789 510297','cyeo_fax' => '','cyeo_email' => 'youth@putneyrotary.org.uk','application_no' => '3923','ribi_club_id' => NULL,'user_id' => '507'),
            array('id' => '451','cyeo_name' => 'Cas Francis','cyeo_sig' => NULL,'cyeo_address' => '32 Oakhurst Close','cyeo_city' => 'Belper','cyeo_state' => 'Derbyshire','cyeo_postcode' => 'DE56 2TR','cyeo_country' => 'England','cyeo_htel' => '01773 821424','cyeo_wtel' => '','cyeo_mobile' => '7747080415','cyeo_fax' => '','cyeo_email' => 'cas@casinspireme.com','application_no' => '3790','ribi_club_id' => NULL,'user_id' => '508'),
            array('id' => '453','cyeo_name' => 'Lynn Washer','cyeo_sig' => NULL,'cyeo_address' => '97 Prospect Road','cyeo_city' => 'Sheffield','cyeo_state' => '','cyeo_postcode' => 'S17 4JB','cyeo_country' => 'UK','cyeo_htel' => '1142366093','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'scarborough.lynn69@gmail.com','application_no' => '3890','ribi_club_id' => NULL,'user_id' => '509'),
            array('id' => '472','cyeo_name' => 'Tony SEMMENS','cyeo_sig' => NULL,'cyeo_address' => '','cyeo_city' => '','cyeo_state' => '','cyeo_postcode' => '','cyeo_country' => '','cyeo_htel' => '+44 1235 815395','cyeo_wtel' => '','cyeo_mobile' => '','cyeo_fax' => '','cyeo_email' => 'lamoais@hotmail.co.uk','application_no' => '3730','ribi_club_id' => NULL,'user_id' => '510')
        );

        DB::table('ribi_cyeo')->truncate();
        foreach ($clubinfo as $item){
//            unset($item['club_name']);
//            unset($item['club_district']);
//            unset($item['club_other_name']);
//            unset($item['club_other_sig']);
//            unset($item['club_president']);
//            unset($item['club_president_sig']);
            $item['ribi_club_id'] = null;
            RibiCyeo::create($item);
        }
    }
}
